import type { Metadata } from "next";
import React from "react";
import { Open_Sans } from "next/font/google";
import StoreProvider from "@/components/StoreProvider";
import configuration from "@/app/configuration.json";
import "./globals.css";

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: configuration.title,
  description: "Generated by create next app",
};

export function generateStaticParams() {
  const stepsIds = [...configuration.steps.map((step) => step.id), "done"];

  return stepsIds.map((slug) => ({
    slug,
  }));
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
